#! /usr/bin/env bash


# Autostart applications

sxhkd -c $XDG_CONFIG_HOME/sxhkd/sxhkdrc &
picom &
feh --no-fehbg --bg-scale ~/pictures/wallpapers/gruvbox-astronaut.png

# Polybar
pkill polybar
$XDG_CONFIG_HOME/polybar/launch.sh

# Set resolution scaling to 130%

xrandr --dpi 130

# Set US and HR keyboard layout
setxkbmap -layout hr,us

# Fix cursor to always theme it
xsetroot -cursor_name left_ptr

# Number of monitors

bspc monitor -d "󰍹 " " " " " "󰊗 " " "


# Config

bspc config border_width         	2
bspc config window_gap           	7

bspc config focus_follows_pointer	false

bspc config focus_follows_pointer	false
bspc config pointer_follows_focus	true

bspc config split_ratio          0.55
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config paddingless_monocle  true
bspc config single_monocle	 false
bspc config presel_feedback	 true

# Configure floating windows manipulation

bspc config pointer_modifier     mod1
bspc config pointer_action1      move
bspc config pointer_action2      resize_side
bspc config pointer_action3      resize_corner

# Windows color (Gruvbox-material)

bspc config normal_border_color 	"#7daea3"
bspc config focused_border_color 	"#d8a657"

# Application rules

# Remove all rules first
bspc rule -r *:*

bspc rule -a Galculator state=floating layer=normal center=true
bspc rule -a KeePassXC state=floating layer=normal rectangle=1800x1000+160+90 desktop='^5' follow=on center=true
bspc rule -a Firefox layer=normal desktop='^2' follow=on
bspc rule -a Thunar state=floating layer=normal rectangle=1800x1000+160+90 desktop='^3' follow=on center=true

# Flatpak rules
bspc rule -a steam state=floating layer=normal rectangle=1920x1080+160+98 desktop='^4' follow=on center=true
bspc rule -a Lutris state=floating layer=normal rectangle=1920x1080+160+98 desktop='^4' follow=on center=true
bspc rule -a bottles state=floating layer=normal rectangle=1920x1080+160+98 center=true
bspc rule -a heroic state=floating layer=normal desktop='^4' follow=on center=true
bspc rule -a warehouse state=floating layer=normal center=true
bspc rule -a com.github.tchx84.Flatseal state=floating layer=normal center=true
