#!/bin/bash

# #####    ##    ####  #    # #####   ####
# #    #  #  #  #      #    # #    # #    #
# #####  #    #  ####  ###### #    # #
# #    # ######      # #    # #####  #
# #    # #    # #    # #    # #   #  #    #
# #####  #    #  ####  #    # #    #  ####
#
# My bash config


# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# ignore upper and lowercase when TAB completion
bind "set completion-ignore-case on"

unset HISTFILE

#################

# => ALIASES

#################

# root privileges
alias doas="doas --"

# xbps package manager
alias xi='doas xbps-install'
alias xr='doas xbps-remove'
alias xq='xbps-query'

# using "eza" as "ls"
alias ls='eza --color=always --group-directories-first'
alias ll='eza -l --color=always --group-directories-first'

# colorize grep output (good for log files)
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# adding flags to some commands
alias cp='cp -i'
alias mv='mv -i'
alias df='df -h'
alias free='free -m'

# navigation
alias home='cd ~'
alias ..='cd ..'
alias ...='cd ../..'
alias .3='cd ../../..'

# shutdown or reboot
alias ssn="doas shutdown now"
alias sr="doas reboot"

# other
alias wget="wget --hsts-file='$XDG_CACHE_HOME/wget-hsts'"

###################

# => Functions

###################

# Extract various archives file types
ex ()
{
    if [ -f "$1" ] ; then
        case $1 in
            *.tar.bz2)  tar xjf "$1"  ;;
            *.tar.gz)   tar xzf "$1"  ;;
            *.bz2)      bunzip2 "$1"  ;;
            *.gz)       gunzip  "$1"  ;;
            *.tar)      tar xf  "$1"  ;;
            *.tbz2)     tar xjf "$1"  ;;
            *.tgz)      tar xzf "$1"  ;;
            *.zip)      unzip   "$1"  ;;
            *.7z)       7z x    "$1"  ;;
            *.tar.xz)   tar xf  "$1"  ;;
            *.tar.zst)  unzstd  "$1"  ;;
            *)          echo "'$1' cannot be extracted via ex()" ;;
        esac
    else
        echo "'$1' is not a valid file"
    fi
}

# Create a ZIP archive of a file or folder
makezip() { zip -r "${1%%/}.zip" "$1" ; }


##################

# => Prompt

##################

# Comment it out if using starship prompt

# PS1='[\u@\h \W]\$ '

# Starship prompt
eval "$(starship init bash)"
